"""Tests for src/breach/classifier.py — target: 15 tests, ≥95% coverage."""

import pytest

pytestmark = pytest.mark.skip(reason="Classifier implementation pending — scaffold phase")


class TestBreachClassifier:
    def test_basic_contact_low_records_encrypted_returns_low(self) -> None: ...

    def test_financial_1000_records_unencrypted_returns_high(self) -> None: ...

    def test_biometric_5000_special_unencrypted_returns_critical(self) -> None: ...

    def test_criminal_data_returns_high_or_critical(self) -> None: ...

    def test_encryption_reduces_total_score(self) -> None: ...

    def test_special_category_increases_score_by_20(self) -> None: ...

    def test_scale_score_increases_with_record_count(self) -> None: ...

    def test_score_clamped_between_0_and_100(self) -> None: ...

    def test_critical_requires_both_ico_and_subject_notification(self) -> None: ...

    def test_high_severity_requires_ico_notification_only(self) -> None: ...

    def test_special_category_always_triggers_ico_notification(self) -> None: ...

    def test_zero_records_handled_without_exception(self) -> None: ...

    def test_result_reasoning_is_non_empty_string(self) -> None: ...

    def test_result_includes_at_least_one_recommended_action(self) -> None: ...

    def test_breakdown_fields_sum_to_total_score(self) -> None: ...
